export const CONTINENTS = [
  "north_america",
  "south_america",
  "europe",
  "africa",
  "asia",
  "australia",
] as const;

export type ContinentId = (typeof CONTINENTS)[number];

export const CONTINENT_BONUSES: Record<ContinentId, number> = {
  north_america: 5,
  south_america: 2,
  europe: 5,
  africa: 3,
  asia: 7,
  australia: 2,
};

export const TERRITORY_IDS = [
  "alaska",
  "northwest_territory",
  "greenland",
  "alberta",
  "ontario",
  "quebec",
  "western_united_states",
  "eastern_united_states",
  "central_america",
  "venezuela",
  "peru",
  "brazil",
  "argentina",
  "iceland",
  "great_britain",
  "scandinavia",
  "ukraine",
  "northern_europe",
  "western_europe",
  "southern_europe",
  "north_africa",
  "egypt",
  "east_africa",
  "congo",
  "south_africa",
  "madagascar",
  "ural",
  "siberia",
  "yakutsk",
  "kamchatka",
  "irkutsk",
  "mongolia",
  "japan",
  "afghanistan",
  "middle_east",
  "india",
  "siam",
  "china",
  "indonesia",
  "new_guinea",
  "western_australia",
  "eastern_australia",
] as const;

export type TerritoryId = (typeof TERRITORY_IDS)[number];

export const TERRITORY_TO_CONTINENT: Record<TerritoryId, ContinentId> = {
  alaska: "north_america",
  northwest_territory: "north_america",
  greenland: "north_america",
  alberta: "north_america",
  ontario: "north_america",
  quebec: "north_america",
  western_united_states: "north_america",
  eastern_united_states: "north_america",
  central_america: "north_america",
  venezuela: "south_america",
  peru: "south_america",
  brazil: "south_america",
  argentina: "south_america",
  iceland: "europe",
  great_britain: "europe",
  scandinavia: "europe",
  ukraine: "europe",
  northern_europe: "europe",
  western_europe: "europe",
  southern_europe: "europe",
  north_africa: "africa",
  egypt: "africa",
  east_africa: "africa",
  congo: "africa",
  south_africa: "africa",
  madagascar: "africa",
  ural: "asia",
  siberia: "asia",
  yakutsk: "asia",
  kamchatka: "asia",
  irkutsk: "asia",
  mongolia: "asia",
  japan: "asia",
  afghanistan: "asia",
  middle_east: "asia",
  india: "asia",
  siam: "asia",
  china: "asia",
  indonesia: "australia",
  new_guinea: "australia",
  western_australia: "australia",
  eastern_australia: "australia",
};

export const CONTINENT_TERRITORIES: Record<ContinentId, TerritoryId[]> = {
  north_america: [
    "alaska",
    "northwest_territory",
    "greenland",
    "alberta",
    "ontario",
    "quebec",
    "western_united_states",
    "eastern_united_states",
    "central_america",
  ],
  south_america: ["venezuela", "peru", "brazil", "argentina"],
  europe: [
    "iceland",
    "great_britain",
    "scandinavia",
    "ukraine",
    "northern_europe",
    "western_europe",
    "southern_europe",
  ],
  africa: [
    "north_africa",
    "egypt",
    "east_africa",
    "congo",
    "south_africa",
    "madagascar",
  ],
  asia: [
    "ural",
    "siberia",
    "yakutsk",
    "kamchatka",
    "irkutsk",
    "mongolia",
    "japan",
    "afghanistan",
    "middle_east",
    "india",
    "siam",
    "china",
  ],
  australia: [
    "indonesia",
    "new_guinea",
    "western_australia",
    "eastern_australia",
  ],
};

export const ADJACENCY: Record<TerritoryId, TerritoryId[]> = {
  alaska: ["northwest_territory", "alberta", "kamchatka"],
  northwest_territory: ["alaska", "alberta", "ontario", "greenland"],
  greenland: ["northwest_territory", "ontario", "quebec", "iceland"],
  alberta: [
    "alaska",
    "northwest_territory",
    "ontario",
    "western_united_states",
  ],
  ontario: [
    "northwest_territory",
    "greenland",
    "quebec",
    "eastern_united_states",
    "western_united_states",
    "alberta",
  ],
  quebec: ["greenland", "ontario", "eastern_united_states"],
  western_united_states: ["alberta", "ontario", "eastern_united_states", "central_america"],
  eastern_united_states: ["quebec", "ontario", "western_united_states", "central_america"],
  central_america: ["western_united_states", "eastern_united_states", "venezuela"],
  venezuela: ["central_america", "brazil", "peru"],
  peru: ["venezuela", "brazil", "argentina"],
  brazil: ["venezuela", "peru", "argentina", "north_africa"],
  argentina: ["peru", "brazil"],
  iceland: ["greenland", "great_britain", "scandinavia"],
  great_britain: ["iceland", "scandinavia", "northern_europe", "western_europe"],
  scandinavia: ["iceland", "great_britain", "northern_europe", "ukraine"],
  ukraine: [
    "scandinavia",
    "northern_europe",
    "southern_europe",
    "middle_east",
    "afghanistan",
    "ural",
  ],
  northern_europe: ["great_britain", "scandinavia", "ukraine", "southern_europe", "western_europe"],
  western_europe: ["great_britain", "northern_europe", "southern_europe", "north_africa"],
  southern_europe: [
    "western_europe",
    "northern_europe",
    "ukraine",
    "middle_east",
    "egypt",
    "north_africa",
  ],
  north_africa: ["brazil", "western_europe", "southern_europe", "egypt", "east_africa", "congo"],
  egypt: ["north_africa", "southern_europe", "middle_east", "east_africa"],
  east_africa: ["north_africa", "egypt", "middle_east", "madagascar", "south_africa", "congo"],
  congo: ["north_africa", "east_africa", "south_africa"],
  south_africa: ["congo", "east_africa", "madagascar"],
  madagascar: ["south_africa", "east_africa"],
  ural: ["ukraine", "siberia", "china", "afghanistan"],
  siberia: ["ural", "yakutsk", "irkutsk", "mongolia", "china"],
  yakutsk: ["siberia", "irkutsk", "kamchatka"],
  kamchatka: ["yakutsk", "irkutsk", "mongolia", "japan", "alaska"],
  irkutsk: ["siberia", "yakutsk", "kamchatka", "mongolia"],
  mongolia: ["siberia", "irkutsk", "kamchatka", "japan", "china"],
  japan: ["kamchatka", "mongolia"],
  afghanistan: ["ukraine", "ural", "china", "india", "middle_east"],
  middle_east: ["southern_europe", "ukraine", "afghanistan", "india", "east_africa", "egypt"],
  india: ["middle_east", "afghanistan", "china", "siam"],
  siam: ["india", "china", "indonesia"],
  china: ["siam", "india", "afghanistan", "ural", "siberia", "mongolia"],
  indonesia: ["siam", "new_guinea", "western_australia"],
  new_guinea: ["indonesia", "western_australia", "eastern_australia"],
  western_australia: ["indonesia", "new_guinea", "eastern_australia"],
  eastern_australia: ["new_guinea", "western_australia"],
};

export const PLAYER_COLORS = [
  "#e74c3c",
  "#3498db",
  "#2ecc71",
  "#f1c40f",
  "#9b59b6",
  "#e67e22",
];

export const CARD_BONUS_SEQUENCE = [4, 6, 8, 10, 12, 15];
